POST http://localhost:8080/residents/8/relationship
Content-Type: application/json

{
  "familySerialNumber" : 6,
  "relationship" : "spouse"
}

###
PUT http://localhost:8080/residents/8/relationship/6
Content-Type: application/json

{
  "relationship": "mother"
}

###
DELETE http://localhost:8080/residents/8/relationship/6
Content-Type: application/json